spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sulfur?characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000

mybatis:
  mapper-locations: classpath:mappers/*.xml

pagehelper:
  params: count=countSql
  reasonable: true
  returnPageInfo: check
  supportMethodsArguments: true



