spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sulfur?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000

  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 1500
        max-idle: 1000
        max-wait: 5000ms

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml



