spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mappers/*.xml

swagger:
  show: true

token:
  ## token过期时间 单位: 天
  expiration: 7
  secret: cCy75Cn6w7FWRiyuN8QOnTr7HPQsZc


