CREATE TABLE `pro_version` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键 信息id',
  `content` varchar(255) NOT NULL COMMENT '内容',
  `type` varchar(40) DEFAULT NULL COMMENT '类型',
  `ctime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `utime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;